### ISSUE TITLE
Finished frontend and backend auth

### ISSUE THREAD

**Issue by marklee9** [marklee9/LetterNote#2]
Hey Andy,

I think I'm done with auth portion of the project.
I still have to finish up my styling.

Best,

**Comment by andywynkoop** [comment]
Hey Mark,
This looks awesome so far! Here are a few changes to make for the user auth MVP:
- [x] Remove redux logger and all console logs before pushing to production
- [x] Demo User doesn't work; you probably just need to create this user in your production db
- [x] Hitting enter on the sign up form doesn't seem to work (gives 422 error), but clicking the button does. Are they doing different things?
- [x] When I type 'andy' as username and 'password' on password and hit enter I get an 'invalid username/password' error
- [x] When I do the same thing and click the button I get a blank page that say 'this.props.errors.map is not a function'
- [x] I probably should get redirected to the dashboard when I am logged in and go to the splash page
- [x] I shouldn't be able to see the log in or sign up forms when I'm already logged in
- [x] Going to a random route like `/alenqeilhrsafhechrefugbef` should show me a 404 page or redirect to `/`
- [x] Errors should clear when navigating between sign up and log in views

**Comment by marklee9** [comment]
Hi Andy,

I think I fixed all the issues, could you please check? 
And if you could also check my notebook MVP too that would be great.
You can check notebooks by clicking the second from the last button.
I am still working on rendering all notes of selected notebook.

Thanks!

**Comment by andywynkoop** [comment]
Sure I'll check it out right now

**Comment by andywynkoop** [comment]
User auth looks great! Go ahead and create a new issue for the notebook MVP and I'll check it out!
